//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace FRDB_SQLite
{
    #region Contexts

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class FuzzySetLibraryEntities : ObjectContext
    {
        #region Constructors

        /// <summary>
        /// Initializes a new FuzzySetLibraryEntities object using the connection string found in the 'FuzzySetLibraryEntities' section of the application configuration file.
        /// </summary>
        public FuzzySetLibraryEntities()
            : base("name=FuzzySetLibraryEntities", "FuzzySetLibraryEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }

        /// <summary>
        /// Initialize a new FuzzySetLibraryEntities object.
        /// </summary>
        public FuzzySetLibraryEntities(string connectionString)
            : base(connectionString, "FuzzySetLibraryEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }

        /// <summary>
        /// Initialize a new FuzzySetLibraryEntities object.
        /// </summary>
        public FuzzySetLibraryEntities(EntityConnection connection)
            : base(connection, "FuzzySetLibraryEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }

        #endregion

        #region Partial Methods

        partial void OnContextCreated();

        #endregion

        #region ObjectSet Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ContinuousLibrary> ContinuousLibraries
        {
            get
            {
                if ((_ContinuousLibraries == null))
                {
                    _ContinuousLibraries = base.CreateObjectSet<ContinuousLibrary>("ContinuousLibraries");
                }
                return _ContinuousLibraries;
            }
        }
        private ObjectSet<ContinuousLibrary> _ContinuousLibraries;

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DiscreteLibary> DiscreteLibaries
        {
            get
            {
                if ((_DiscreteLibaries == null))
                {
                    _DiscreteLibaries = base.CreateObjectSet<DiscreteLibary>("DiscreteLibaries");
                }
                return _DiscreteLibaries;
            }
        }
        private ObjectSet<DiscreteLibary> _DiscreteLibaries;

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MotherLibrary> MotherLibraries
        {
            get
            {
                if ((_MotherLibraries == null))
                {
                    _MotherLibraries = base.CreateObjectSet<MotherLibrary>("MotherLibraries");
                }
                return _MotherLibraries;
            }
        }
        private ObjectSet<MotherLibrary> _MotherLibraries;

        #endregion
        #region AddTo Methods

        /// <summary>
        /// Deprecated Method for adding a new object to the ContinuousLibraries EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToContinuousLibraries(ContinuousLibrary continuousLibrary)
        {
            base.AddObject("ContinuousLibraries", continuousLibrary);
        }

        /// <summary>
        /// Deprecated Method for adding a new object to the DiscreteLibaries EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDiscreteLibaries(DiscreteLibary discreteLibary)
        {
            base.AddObject("DiscreteLibaries", discreteLibary);
        }

        /// <summary>
        /// Deprecated Method for adding a new object to the MotherLibraries EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMotherLibraries(MotherLibrary motherLibrary)
        {
            base.AddObject("MotherLibraries", motherLibrary);
        }

        #endregion
    }


    #endregion

    #region Entities

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName = "FuzzySetLibraryModel", Name = "ContinuousLibrary")]
    [Serializable()]
    [DataContractAttribute(IsReference = true)]
    public partial class ContinuousLibrary : EntityObject
    {
        #region Factory Method

        /// <summary>
        /// Create a new ContinuousLibrary object.
        /// </summary>
        /// <param name="languisticLabel">Initial value of the LanguisticLabel property.</param>
        /// <param name="bottomLeft">Initial value of the BottomLeft property.</param>
        /// <param name="topLeft">Initial value of the TopLeft property.</param>
        /// <param name="topRight">Initial value of the TopRight property.</param>
        /// <param name="bottomRight">Initial value of the BottomRight property.</param>
        public static ContinuousLibrary CreateContinuousLibrary(global::System.String languisticLabel, global::System.Double bottomLeft, global::System.Double topLeft, global::System.Double topRight, global::System.Double bottomRight)
        {
            ContinuousLibrary continuousLibrary = new ContinuousLibrary();
            continuousLibrary.LanguisticLabel = languisticLabel;
            continuousLibrary.BottomLeft = bottomLeft;
            continuousLibrary.TopLeft = topLeft;
            continuousLibrary.TopRight = topRight;
            continuousLibrary.BottomRight = bottomRight;
            return continuousLibrary;
        }

        #endregion
        #region Primitive Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = true, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.String LanguisticLabel
        {
            get
            {
                return _LanguisticLabel;
            }
            set
            {
                if (_LanguisticLabel != value)
                {
                    OnLanguisticLabelChanging(value);
                    ReportPropertyChanging("LanguisticLabel");
                    _LanguisticLabel = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("LanguisticLabel");
                    OnLanguisticLabelChanged();
                }
            }
        }
        private global::System.String _LanguisticLabel;
        partial void OnLanguisticLabelChanging(global::System.String value);
        partial void OnLanguisticLabelChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.Double BottomLeft
        {
            get
            {
                return _BottomLeft;
            }
            set
            {
                OnBottomLeftChanging(value);
                ReportPropertyChanging("BottomLeft");
                _BottomLeft = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BottomLeft");
                OnBottomLeftChanged();
            }
        }
        private global::System.Double _BottomLeft;
        partial void OnBottomLeftChanging(global::System.Double value);
        partial void OnBottomLeftChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.Double TopLeft
        {
            get
            {
                return _TopLeft;
            }
            set
            {
                OnTopLeftChanging(value);
                ReportPropertyChanging("TopLeft");
                _TopLeft = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TopLeft");
                OnTopLeftChanged();
            }
        }
        private global::System.Double _TopLeft;
        partial void OnTopLeftChanging(global::System.Double value);
        partial void OnTopLeftChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.Double TopRight
        {
            get
            {
                return _TopRight;
            }
            set
            {
                OnTopRightChanging(value);
                ReportPropertyChanging("TopRight");
                _TopRight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TopRight");
                OnTopRightChanged();
            }
        }
        private global::System.Double _TopRight;
        partial void OnTopRightChanging(global::System.Double value);
        partial void OnTopRightChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.Double BottomRight
        {
            get
            {
                return _BottomRight;
            }
            set
            {
                OnBottomRightChanging(value);
                ReportPropertyChanging("BottomRight");
                _BottomRight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BottomRight");
                OnBottomRightChanged();
            }
        }
        private global::System.Double _BottomRight;
        partial void OnBottomRightChanging(global::System.Double value);
        partial void OnBottomRightChanged();

        #endregion

    }

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName = "FuzzySetLibraryModel", Name = "DiscreteLibary")]
    [Serializable()]
    [DataContractAttribute(IsReference = true)]
    public partial class DiscreteLibary : EntityObject
    {
        #region Factory Method

        /// <summary>
        /// Create a new DiscreteLibary object.
        /// </summary>
        /// <param name="languisticLabel">Initial value of the LanguisticLabel property.</param>
        public static DiscreteLibary CreateDiscreteLibary(global::System.String languisticLabel)
        {
            DiscreteLibary discreteLibary = new DiscreteLibary();
            discreteLibary.LanguisticLabel = languisticLabel;
            return discreteLibary;
        }

        #endregion
        #region Primitive Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = true, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.String LanguisticLabel
        {
            get
            {
                return _LanguisticLabel;
            }
            set
            {
                if (_LanguisticLabel != value)
                {
                    OnLanguisticLabelChanging(value);
                    ReportPropertyChanging("LanguisticLabel");
                    _LanguisticLabel = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("LanguisticLabel");
                    OnLanguisticLabelChanged();
                }
            }
        }
        private global::System.String _LanguisticLabel;
        partial void OnLanguisticLabelChanging(global::System.String value);
        partial void OnLanguisticLabelChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = true)]
        [DataMemberAttribute()]
        public global::System.String Values
        {
            get
            {
                return _Values;
            }
            set
            {
                OnValuesChanging(value);
                ReportPropertyChanging("Values");
                _Values = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Values");
                OnValuesChanged();
            }
        }
        private global::System.String _Values;
        partial void OnValuesChanging(global::System.String value);
        partial void OnValuesChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = true)]
        [DataMemberAttribute()]
        public global::System.String Memberships
        {
            get
            {
                return _Memberships;
            }
            set
            {
                OnMembershipsChanging(value);
                ReportPropertyChanging("Memberships");
                _Memberships = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Memberships");
                OnMembershipsChanged();
            }
        }
        private global::System.String _Memberships;
        partial void OnMembershipsChanging(global::System.String value);
        partial void OnMembershipsChanged();

        #endregion

    }

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName = "FuzzySetLibraryModel", Name = "MotherLibrary")]
    [Serializable()]
    [DataContractAttribute(IsReference = true)]
    public partial class MotherLibrary : EntityObject
    {
        #region Factory Method

        /// <summary>
        /// Create a new MotherLibrary object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="languisticLabel">Initial value of the LanguisticLabel property.</param>
        public static MotherLibrary CreateMotherLibrary(global::System.Int32 id, global::System.String languisticLabel)
        {
            MotherLibrary motherLibrary = new MotherLibrary();
            motherLibrary.ID = id;
            motherLibrary.LanguisticLabel = languisticLabel;
            return motherLibrary;
        }

        #endregion
        #region Primitive Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = true, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.String LanguisticLabel
        {
            get
            {
                return _LanguisticLabel;
            }
            set
            {
                OnLanguisticLabelChanging(value);
                ReportPropertyChanging("LanguisticLabel");
                _LanguisticLabel = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LanguisticLabel");
                OnLanguisticLabelChanged();
            }
        }
        private global::System.String _LanguisticLabel;
        partial void OnLanguisticLabelChanging(global::System.String value);
        partial void OnLanguisticLabelChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = true)]
        [DataMemberAttribute()]
        public global::System.String FuzzySet
        {
            get
            {
                return _FuzzySet;
            }
            set
            {
                OnFuzzySetChanging(value);
                ReportPropertyChanging("FuzzySet");
                _FuzzySet = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FuzzySet");
                OnFuzzySetChanged();
            }
        }
        private global::System.String _FuzzySet;
        partial void OnFuzzySetChanging(global::System.String value);
        partial void OnFuzzySetChanged();

        #endregion

    }

    #endregion

}
